### ISSUE TITLE
Localization of docs

### ISSUE THREAD

**Issue by Blueberryy** [SC2Mapster/blizzard-tutorials#7]
Can you implement language system for your wiki?
readthedocs has locale thing and i hope you will add it in some next patch

**Comment by Talv** [comment]
Sorry, not going to happen:
- It'd add extra work. And at the current state this repo/docs is barely being taken care of.
- Potentially screenshots of SC2Editor would have to be localized too, and if so these would potentially need to be redone or edited - with some extra captions, to outline/translate whatever screenshots shows.
- Using SC2Editor in non-english is just bad idea to begin with, since it uses machine translation (from previous generation) for a lot of stuff. It makes stuff confusing.
- ... this list could go on, but above is enough.
